default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_DEV'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB_TESt'] %>_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB_PROD'] %>

